create table if not exists t_user
(
    id         bigint generated by default as identity
    constraint t_user_pkey
    primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255)
    );

alter table t_user
    owner to postgres;

create table if not exists t_role
(
    id   bigint not null
    constraint t_role_pkey
    primary key,
    name varchar(255)
    );

alter table t_role
    owner to postgres;

create table if not exists t_user_roles
(
    user_id  bigint not null
    constraint fkpqntgokae5e703qb206xvfdk3
    references t_user,
    roles_id bigint not null
    constraint fkj47yp3hhtsoajht9793tbdrp4
    references t_role,
    constraint t_user_roles_pkey
    primary key (user_id, roles_id)
    );

alter table t_user_roles
    owner to postgres;

create table if not exists t_product
(
    id         bigint  not null
    constraint t_product_pkey
    primary key,
    brand_name varchar(255),
    category   varchar(255),
    path       varchar(255),
    price      integer not null
    );

alter table t_product
    owner to postgres;

create table if not exists t_basket
(
    id         bigint generated by default as identity
    constraint t_basket_pkey
    primary key,
    count      integer,
    sum        integer,
    product_id bigint
    constraint fkcs9a66i08spu3rpy5qi9yiw7o
    references t_product
);

alter table t_basket
    owner to postgres;

create table if not exists t_history_of_orders
(
    id            integer not null
    constraint t_history_of_orders_pkey
    primary key,
    count         integer not null,
    creation_date varchar(255),
    sum           integer not null,
    product_id    bigint
    constraint fkdwtqgub2l9fiolgbwwtrithtm
    references t_product,
    user_id       bigint
    constraint fkl9j18rku5mmcoykd813qsxb8w
    references t_user
    );

alter table t_history_of_orders
    owner to postgres;


INSERT INTO public.t_role (id, name) VALUES (1, 'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO public.t_role (id, name) VALUES (2, 'ROLE_ADMIN') ON CONFLICT DO NOTHING;


INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (1, '5th Avenue', 'Медицинские очки', '/img/5thAvenue.jpg', 2397) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (2, 'Julius', 'Медицинские очки', '/img/Julius.jpg', 4893) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (3, 'Marc Jacobs', 'Солнцезащитные очки', '/img/MarcJacobs.jpg', 6930) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (4, 'Heritage', 'Медицинские очки', '/img/Heritage.jpg', 3995) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (6, 'C-Line', 'Медицинские очки', '/img/Cline.jpg', 3493) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (5, 'Unofficial ', 'Медицинские очки', '/img/Unofficial.jpg', 4490) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (7, 'Moschino', 'Медицинские очки', '/img/Mochino.jpg', 10990) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (8, 'Vogue', 'Солнцезащитные очки', '/img/Vogue.jpg', 4450) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (9, 'Armani Exchange', 'Солнцезащитные очки', '/img/Armani.jpg', 6675) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (10, 'Polaroid', 'Солнцезащитные очки', '/img/Polaroid.png', 5175) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (11, 'Victoria’s Secret', 'Солнцезащитные очки', '/img/Victoria.jpg', 7900) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (12, 'Solaris', 'Солнцезащитные очки', '/img/Solaris.jpg', 2900) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (13, 'iWear Oxygen 6', 'Контактные линзы', '/img/iWear Oxygen 6.jpg', 2990) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (14, 'Johnson & Johnson Acuvue Oasys Hydraclear 6', 'Контактные линзы', '/img/JJ.jpg', 1890) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (15, 'Alcon Air Optix plus HydraGlyde 6', 'Контактные линзы', '/img/Alcon.jpg', 2890) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (16, 'Cooper Vision Clarity 1-Day Multifocal 30', 'Контактные линзы', '/img/Cooper2.jpg', 2890) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (17, 'Johnson & Johnson 1-Day Acuvue Moist 90', 'Контактные линзы', '/img/JJ2.jpg', 5490) ON CONFLICT DO NOTHING;
INSERT INTO public.t_product (id, brand_name, category, path, price) VALUES (18, 'iWear Oxygen for Astigmatism 3', 'Контактные линзы', '/img/iWear2.jpg', 1990) ON CONFLICT DO NOTHING;